version: '3.8'

networks:
  my-network:
    name: my-network
    external: true

services:
  payment-service:
    build: .
    image: payment-service
    networks:
      - my-network

    ports:
      - 5020:5000

    
  ngrok:
      image: ngrok/ngrok:alpine
      volumes:
        - ../ngrok.yml:/app/ngrok.yml
      command:
        - start
        - --all
        - --config
        - /app/ngrok.yml
      networks:
        - my-network