version: '3.8'

networks:
  my-network:
    name: my-network

volumes:
  mysql_data:

services:
  mysqlsvc:
    build:
      context: .
      dockerfile: combined.Dockerfile
    restart: always
    ports:
      - "3310:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    stop_grace_period: 15s
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db_data/flight_data.csv:/var/lib/mysql-files/f_data.csv:rw
      - ./db_data/booking_data.csv:/var/lib/mysql-files/b_data.csv:rw
      - ./db_data/passenger_data.csv:/var/lib/mysql-files/p_data.csv:rw
      - ./db_data/seat_data.csv:/var/lib/mysql-files/s_data.csv:rw
    networks:
      - my-network