version: '3.8'

services:

  # RabbitMQ service container
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-mgmt
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - HOSTNAME=esd-rabbit
    hostname: esd-rabbit